image: alpine:latest

before_script:
  - apk -q add make

build:
  stage: build
  script:
    - make
    - make DESTDIR=mobile-config-firefox install
  artifacts:
    paths:
      - mobile-config-firefox
