image: alpine:latest

build:
  before_script:
    - apk -q add make
  script:
    - make
    - make DESTDIR=mobile-config-firefox install
  artifacts:
    paths:
      - mobile-config-firefox

lint:
  before_script:
    - apk -q add grep
  script:
    - .ci/lint.sh
